// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssbmknunjusvgvvpnxrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzYm1rbnVuanVzdmd2dnBueHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTk4NjYsImV4cCI6MjA2NTQ3NTg2Nn0.rdxklmpvKxTKist8pVSxO8sKxCMQc_kTldB_V_DJgJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);